// Eduard Ciofu All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace Frontend
{
	namespace WidgetStack
	{
		FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Modal);
		FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameMenu);
		FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameHUD);
		FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend);
	}

	namespace Widget
	{
		FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PressAnyKeyScreen);
		FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MainMenuScreen);
		FRONTENDUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConfirmScreen);
	}
}